# Generated by Django 2.2.6 on 2020-12-09 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredient', models.TextField()),
                ('preparation', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('portions', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
