# Generated by Django 2.2.6 on 2020-12-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_recipe_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo_recipe',
            field=models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/'),
        ),
    ]
