# Generated by Django 2.2.6 on 2020-12-16 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_recipe_photo_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
